version: "3"
services:
  backend:
    container_name: guate_comenta
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
     - redis
     - mongo
  redis:
    image: redis
  mongo:
    image: mongo
    ports:
      - "27017:27017"